### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by ronea23** [waarp/WaarpR66#168]
As per your suggestions i have removed my local configurations the server started.

1.  I could able to launch the ADMINGUI, but the xml editor is not being opened.
2.  I could not able to launch the web-app.
3.  How to run R66 as client ( what packages are required) , on my local pc i ll put server and on VM i ll run a client, so how to work out that arch?
4.  How to establish the connection between the server and client.

Regards,
Ronald

**Comment by fredericBregier** [comment]
1) XML Editor is optional. On my PC (Windows too), it is working. Maybe you don't have all jar in your path (all jars in lib directory plus one for the database you choose, either PostgreSQL or H2 Database).
If you can't, there is still other solutions:
a) using JAXE editor (configuration provided too in xample directory)
b) using another XML editor compatible with XSD files
c) using a simple text editor (as Notepad ++ or whatsoever)

2) Web-app (I suppose admin web app only on R66 server side) is available only if the R66 server is started of course. So you have to finish the configuration first

3) The package for the client are the same (except database if your client will not have any database). The client could have the very same configuration file than the server (acting as client for this server) or another one (look at examples in config directory).

In order the client can connect to the server (the reverse is not possible, as in FTP: a client can only do remote connection from it, no getting request from outside), the server and the client must know each other (authentication). So in the database (or in the xml file for the client), both the server and the client must be known.
After, it is a matter of port opened, the one you choose. If you choose for instance 6666 for the server in SSL mode, the server must allow incoming connection on this port. Of course, the client must allow outgoing connection too on the very same port.
Running in a VM or directly in the host has no issue (R66 runs using Java at least 1.6, but better 1.7 and higher, and was prooved ok on Linux - Debian as Ubuntu or Redhat as CentOs based, Windows, AIX, Solaris, even some mainframe as Zseries -).

4) Once the configuration is done (both server and client), you can check if the connection is ok by sending a simple message from client to server (r66mesg). If will test all the connection, authentication on both side but do nothing except a simple ping/pong from client to server and back.

**Comment by ronea23** [comment]
So, Server to Client Communication is not possible ?

Only Client to Server is possible ?

Can i leave the client as a windows service and then try to connect from server ?

Regards,
Ronald

**Comment by fredericBregier** [comment]
Server to Client is not possible means the server cannot initiate a transfer to a client.
But a client can initate a transfer to a server, whatever the way (get/put).
Of course, a server can contact another server.
This is the same logic as FTP (FTP Server and FTP client) or HTTP (Web server and Web client).

If you want to be able to contact a R66 partner, it must be a server. So if your scenario is to contact the client from the server (initiative from the server), then the client must be a server too.

**Comment by ronea23** [comment]
rightly pointed,,, coz two way connections are only possible if server is on either sides..

So if run the partner, would i be able to run external commands ?

Regards,
Ronald

**Comment by fredericBregier** [comment]
External commands are linked to "rules" (the name given to the contract of transfer used).
If a rule specify to execute something (a task), then it will be executed. See here for the task explanation:
http://waarp.github.io/Waarp/WaarpR66TaskAllOptions.html
and of course http://waarp.github.io/Waarp/R66Definitions.html

A rule applied locally (depending if the server/client is sender or receiver), according to the local definition of the rule (or globally if the database is shared). Therefore even a client can execute some tasks through a rule.

EXEC is for instance a TASK in a rule to execute a local program (local to the partner, whatever client/server).
A Rule defines 5 different type of task sets:
PreRecv = before reception
PostRecv = after reception
PreSend = before sending
PostSend = after sending
ErrorTask = in case an error occurs

**Comment by ronea23** [comment]
So file transfers cant be initiated from the server, if it is in client mode. If i put in server mode i can do the file transfer.

What would be the minimum bandwidth to do the file transfer ?

My arch is simple, pls gimme your suggestions which is very highly valuable.


1. Assuming 1 central server (Where files gonna be stored ) , 100 clients ( say from PC's / agents ) planning to pull files without any user interactions from the client ( meaning on the PC no one will interrupt for push / receive the files). 
2. Schedule file pull tasks on the central server to initiate file pull from the clients ( partners , as clients can only send ).
3. Remote commands to be executed on the clients (partners), say like windows commands ( dir /s, reg query, tasklist etc )
4. Reporting on file transfers and its failures.

Please gimme your suggestions on these topics.

Regards,
Ronald

**Comment by ronea23** [comment]
And under the hood, i want to implement R66 HTTP not FTP, how can restrict only HTTP ?

Regards,
Ronald

**Comment by fredericBregier** [comment]
The minimal bandwidth is roughly around 2 KB/s. It depends on the packet size (default 64KB) and the timeout (default 30s), since a timeout occurs if no packet is received during 30s (64KB/30s ~2KB/s).

What you want to do seems feasable.
Considering remote execution, note that by default, Rules are only executed when a file transfer occurs, meaning you can't execute a remote task without going through a transfer.
Another option is to consider "BusinessRequest" (org.waarp.openr66.client.BusinessRequest) which allows to run remote Java command of your own through a simple request (note the requester must be allowed in Business system option). This "BusinessRequest" allows to mix specific business actions within R66 out of file transfer.

Regarding HTTP, there is no "publicly" available implementation yet.
Currently R66 uses R66 protocol (which is neiter FTP, neither HTTP). FTP is in the gateway in order to allow to pass from one protocol to another, but in your scenario, I don't believe it is useful.

**Comment by ronea23** [comment]
great !! understood, pls give me an example of configuration, say i want to pull files on a daily basis from different machines automatically, assuming the trigger (command) is from the central server, the other agents(different pc's running r66 server) should send the files.

need to do any anything extra from the product ?

**Comment by fredericBregier** [comment]
Well, giving such an example might be long... ;-)
The main idea I have is the following:
- create a Rule that will get the file available from each partner (client as server) : 

   1. this rule shall be of RECV format (since the server will ask to GET (recv) a file from partner)
   2. this rule could have pre/post command if necessary on both side (server/partner) (for instance PRE-SEND to prepare the file on partner side or POST-RECV to act once the file is received on server side)
   3. change if necessary the "out" path in the rule to reflect the directory where the file shall be before sending on partner side, and "in" path in the rule to reflect the directory where the file shall be after the sending
   4. eventually add extra commands as POST-SEND (for instance deleting the file sent on partner side)
   5. add Error part (at least logging for instance or any action to take when an error occurs)

The rule is not necessarily the same on both sides: the rule is evaludated locally
  1. the server could have only RECV part filled
  2. partners could have only SEND part filled
  3. both must have the same name and same way (RECV mode)

- create a script (bat file) that will do the following: several options exist (pseudo codes)

  1. launch a loop on all clients/partners id and launch unitary synchronous recv command

          FOR your loop on IDs
             r66syncsend -to ID -rule yourrule -file theFilenameYouWant

     This option will directly receive the file from each r66syncsend command, without passing through the server (the command is standalone, as a client).

  2. launch a loop on all clients/partners id and launch unitary asynchronous recv command

          FOR your loop on IDs
             r66send -to ID -rule yourrule -file theFilenameYouWant

     This option will use the server to get the files, so the command is asynchronous and the result will be in the future, once the server has made it.

  3. launch one synchronous recv command for all partners id

          r66multisyncsend -to ID1,ID2,ID3,ID4,... -rule yourrule -file theFilenameYouWant

     This option will directly receive the file from each implicit r66syncsend command, without passing through the server (the command is standalone, as a client). The difference with the loop in 1 is that the global result is in success only if all recv commands are in success.

  4. launch one asynchronous recv command for all partners id

          r66multisend -to ID1,ID2,ID3,ID4,... -rule yourrule -file theFilenameYouWant

      This option is very similar to the 2, except only one call is made. The results are not dependent each other as in 2.

- now final part, plan this batch file, using whatever scheduler (windows one for instance)


Now it's up to you to try and test. Start first by trying to send a simple message through a bat file to each client (r66mesg command) using the very same logic than in 1 loop. Then try to recv one file from one partner manually, and if it is ok, then make your bat file for all partners.
Good luck !

**Comment by fredericBregier** [comment]
I guess this issue can be closed since no feedback.
If another specific issue comes, just open a new one. ;-)
