### ISSUE TITLE
Can't login on Web Interface

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#173]
Hi,

It's me again. Currently I can't login on web interface using hosta credentials. To be sure of password correctness I have generated ggp file through admin GUI and configured it in OpenR66 authent file for that host.
In my lab installation Web Interface listens in HTTPS on 8067 and hosta on 6666 (no SSL). On failed login, log file returns the following 
`ERROR [org.waarp.openr66.context.authentication.R66Auth] [HttpWorker-45] org.waarp.openr66.context.authentication.R66Auth.connectionHttps(R66Auth.java:308) : Authentication is unacceptable for hosta`
After some reverse engineering I noticed that the error message is returned when port is greater or equal to zero (https://github.com/waarp/WaarpR66/blob/8e4f04fa198230ecf3cfe7cfa98ee75f18354188/src/main/java/org/waarp/openr66/context/authentication/R66Auth.java#L307)
As a workaround I have defined a host with negative port .. and voila I was able to login and modify configuration for hosta .

Am I doing something wrong? Or do you think this is an issue?

Regards

Alex

**Comment by fredericBregier** [comment]
It's not the intended way ;-)

Admin is by default the admin account defined by
     <server>
        <serveradmin>xxx</serveradmin>
        <serverpasswd>pwd<serverpasswd> or <serverpasswdfile>file</serverpasswdfile>

where pwd is the content of the ggp file, of file is the ggp file.

When you don't use the "global" admin account, then you can use "user" accounts which are defined by a "-1" (or less) port. These accounts are not attached to any server but only used to filter access to the user using ROLEs.

See pages:
- Server config : http://waarp.github.io/Waarp/R66ServerConfig.html
- Authentification: http://waarp.github.io/Waarp/R66Authentication.html
- Web Admin (and in particular at the end on Roles) : http://waarp.github.io/Waarp/WaarpR66WebAdministration.html

So you should define an admin account first, using it, then declare if needed extra users with less (or similar right if you put FULLADMIN).

Doing what you've done should let the server as a "client" (no listening port, since port < 0), which you don't want, right ?

Tell me if it is now correct doing this way... I let the issue open till you confirm.

**Comment by alexbarta** [comment]
Yes you're definitely right :) .. I missed "monadmin" superuser. I just needed to replace ggp default serverpasswd with my own key and I was able to login with no problem.

I understand also that if want to create further users I need first to define hosts (clients) with negative ports and manage them with user roles. Is that right?

off-topic: Web interface has HTML default font style (not same font shown here http://a.fsdn.com/con/app/proj/waarp/screenshots/w3-hosts.png ) that looks a bit awkward :S . May I open a separate issue?

Thanks

**Comment by fredericBregier** [comment]
For the extra users, yes you get it right. Creating "pseudo" hosts with negative ports gives extra authentifcation that can be used in the interface. Then using the system menu, you can add specific rights (Roles) to them.

On the font style, yes please, open a new issue on that point, giving an example of "your" screen.
It might be a question of browser too. Mostly, me, I use Chrome, but I know the presentation is almost the same under Firefox, but quite different on IE or Edge due to bootstrap. It might be such an issue, or it might be something totally different, so please give also the browser configuration and the OS you use. Thanks !

So I close this one...

**Comment by fredericBregier** [comment]
By the way, I just look at the font, it seems (if this is the issue) that the font is in majority by default under magic-bootstrap-min.css set as "Open Sans", which is an open font from Google. And I got the very same rendering on Edge, Firefox and Chrome.
Are you using the directory httpadmin or httpadmin-static ? The picture is from httpadmin (using the responsive design).

Let's continue this discussion under your nex issue when it comes ;-)
