### ISSUE TITLE
Font appearance in Web AdminGui

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#174]
Hi,

As promised here the new issue. Font appearance in the Web AdminGui looks a bit different from I have seen so far here http://a.fsdn.com/con/app/proj/waarp/screenshots/w3-hosts.png . Just to give you evidence I have attached some screenshots here below (taken from Chrome, Firefox). 

As you correctly pointed out in my previous issue, the difference is made by "Open Sans" font family in httpadmin/css/magic-bootstrap-min.css, changing that value in the web editor results in a change of font appearance. Also I have configured httpadmin (not static) responsive setup in my server config.

Regards

Alex

![image](https://cloud.githubusercontent.com/assets/9393789/12321771/3ac75c40-bab0-11e5-8f89-c689d17fbaa4.png)

![image](https://cloud.githubusercontent.com/assets/9393789/12321790/643150f4-bab0-11e5-9f2c-d925e8e9dcd3.png)

**Comment by fredericBregier** [comment]
Very very strange indeed !
Googling a bit (ok, It's google's font), I found the following:

http://stackoverflow.com/questions/21678458/google-font-not-working-with-bootstrap

Where the first response gives some way to try to fix it.
Since it is working on mine install, I would suggest you to try to add the content of: http://fonts.googleapis.com/css?family=Open+Sans:400,600
within (at the end probably) css/bootstrap-multiselect.min.css (which is the last css file that should be loaded).

If this works, then I could try to patch the admin web by including statically the font (as described here http://alexwenzel.de/2014/270/use-fonts-from-google-fonts-library-local ) in the distribution.

Could you try the short way first (modifying temporarily the css file to add links to google fonts) ?

I join too my

**Comment by alexbarta** [comment]
Hi,

Indeed adding those google css **https://**fonts.googleapis.com (my browser connects to https waarp gui so it blocks insecure http calls) to both css/bootstrap-multiselect.min.css  css/magic-bootstrap-min.css solved the issue. I changed both since some htmls import only css/magic-bootstrap-min.css. I attach also a screen of what I see now.
![image](https://cloud.githubusercontent.com/assets/9393789/12354097/ef4817b6-bb93-11e5-9654-c7df9292553b.png)

ps I tell you more, http://waarp.github.io/Waarp/ seems to have the same problem..
![image](https://cloud.githubusercontent.com/assets/9393789/12354218/b125ace0-bb94-11e5-812a-373c90615e9d.png)



Thanks

Alex

**Comment by fredericBregier** [comment]
OK Thanks for this full report ! Very helpful !
I will send the correction to the main build such that the next release is ok !
Thanks for reporting again !

I will let this issue opened until the new version is out...

**Comment by fredericBregier** [comment]
New version published! ;-)
So I close this one. Feel free to open a new one it if an issue is still there.
