### ISSUE TITLE
R66BusinessInterface

### ISSUE THREAD

**Issue by Astr0boy** [waarp/WaarpR66#175]
Hello,

I would like to create my own R66BusinessInterface but don't really see how to link the R66BusinessInterface to a R66Session without interfering with the source code...
Can you please provide me some clues ?

**Comment by fredericBregier** [comment]
Hi,
I must admit that this part of the code was changed sometimes in the past since no one had the usage requirement. This was made wrong.
The idea, as in the Waarp FTP Gateway, was to change the server main initialize method according to the needs by something like this:

    public static boolean initialize(String config) {
        if (logger == null) {
            logger = WaarpLoggerFactory
                    .getLogger(R66Server.class);
        }
        if (!FileBasedConfiguration
                .setConfigurationServerFromXml(Configuration.configuration, config)) {
            logger
                    .error(Messages.getString("Configuration.NeedCorrectConfig")); //$NON-NLS-1$
            return false;
        }
        Configuration.configuration.r66BusinessFactory = new MyBusinessFactory(); // ADDED
        try {
            Configuration.configuration.serverStartup();
        } catch (Throwable e) {
            logger
                    .error(Messages.getString("R66Server.StartError"), e); //$NON-NLS-1$
            R66ShutdownHook.terminate(false);
            return false;
        }
        return true;
    }

And to do that, you need to change the Configuration class to the following:

    public R66BusinessFactoryInterface r66BusinessFactory = new R66DefaultBusinessFactory();

instead of

    private final R66BusinessFactoryInterface r66BusinessFactory = new R66DefaultBusinessFactory();

We will include this light modification in Configuration class in the next release.

However, note that the reason of this old change is that most of the time, the best thing to do is to interact directly in the rule by adding his own extra command, using JAVAEXEC. 

In `org.waarp.openr66.context.javatask` you will find examples as AddDigestJavaTask and AddUuidJavaTask classes. You can freely add your own Jar with your own classes extending AbstractExecJavaTask to make extra commands in Java, either as Pre/Post Recv/Send or Error actions. Most of the time, this is fully enough, so the reason we disabled long time ago the businessFactory. 

However, if you have a good reason to use the businessFactory, making the changes I show you will be enough. The main issue with that is that you need to write your own "main" R66Server start class, since it is not today configurable through the xml configuration file.

Could you tell us what is the usage so to determine if we need to investigate the "xml" configuration part for this old usage ?

**Comment by Astr0boy** [comment]
Bonjour Frédéric,

Thanks for your quick reply!  The "final R66BusinessFactoryInterface" was
bothering me but at least it's clear now :)
So at the end, I used a post actions using JAVAEXEC as advise. However when
I look at the AddUuidJavaTask source code I can see that it extends
AbstractExecJavaTask and not implements R66Runnable as stated in the
documentation (http://waarp.github.io/Waarp/WaarpR66TaskAllOptions.html).
Regarding the usage, I'll contact you in a different email to give you more
inputs.





2016-02-05 8:24 GMT+01:00 Frédéric Brégier <notifications@github.com>:

**Comment by fredericBregier** [comment]
AbstractExecJavaTask is an extend of R66Runnable. It is one of the correct way to quickly implement such a Java Task, if the default other methods are acceptable as such.
So R66Runnable is a simple interface, while AbstractExecJavaTask is the default base implementation where most of the time only the run method is to be overriden.

**Comment by fredericBregier** [comment]
To be correct, AbstractExecJavaTask includes by default some methods that are helpers for R66Business part, (not useful in your cases) as `validate`, `finalvalidate`, .... For the example, AddUuidJavaTask does not use those extra methods. And we could use a direct `implements R66Runnable` with exactly the same result. Generally we do use the AbstractExecJavaTask in order to allow to use them in R66Business cases as well as in EXECJAVA tasks. In this specific case, it is a non sens, which could lead to incorrect comprehension.

**Comment by Astr0boy** [comment]
Ok it's clear. Thanks Frédéric.
