### ISSUE TITLE
No ERRORTASK triggered for transfer initiated by R66 client

### ISSUE THREAD

**Issue by Astr0boy** [waarp/WaarpR66#182]
Hi Frédéric,

I did some tests where I initiated some transfers from a R66 client with database connection.
The remote server is down, therefore the transfers failed on go in internal status INERROR : Connection Impossible which is expected.
However, no error task is triggered even if the rule has some execjava for Recv Error / Send Error.
Is it the "normal" behavior ?

**Comment by fredericBregier** [comment]
Hmm let me check. I'm not sure the Error steps are running in this case. It might be a bug.

**Comment by fredericBregier** [comment]
OK, I check it. This is normal (at least from our perspective) since:

- as long as the connection cannot be done, the request is not started, therefore there is no task error
- once the connection is done, if an error occurs (whatever), then the task error is executed

So there is only an exception OpenR66ProtocolNoConnectionException that is raised and must be catch. Note that 3 tries are done before this exception occurs.

I can check if it is possible to execute however the error task in such condition. Is it useful for you ?

**Comment by fredericBregier** [comment]
Quick Note (sunday ;-)

I believe it is quite easy to manage to run task error in such cases. Note however that there is no Session so there might be some side effects (but I guess limited or even none).

I will propose this evolution.

**Comment by Astr0boy** [comment]
Great! Thanks Frédéric. In the meanwhile, I'm catching the R66Result and will update the transfer status accordingly.

**Comment by bcarlin** [comment]
Thé fix has been merged un master. The final version will be released un the next couple of weeks.
