### ISSUE TITLE
Use external datasource instead of XML config db connection

### ISSUE THREAD

**Issue by Astr0boy** [waarp/WaarpR66#183]
Hi Frédéric,

This is more an evolution that an issue.
Is there a way to add as an option to use an external datasource instead of using the database connection used in the XML configuration file ?

**Comment by fredericBregier** [comment]
Well, it might be possible but currently the logic is that the "server" is standalone, and then the clients (whatever application or command) interact with server (either using DirectTransfer, either prefereably using SubmitTransfer).
Therefore in this case, the "server" part should not be "embedded", even if it is possible.
On "client" side, it is understandable to make such that database is opened through a datasource (I suppose like in Tomcat, right ?).

There could be some issues (as Waarp include some test of connectivity, handling the pooling of the database connections, ...), but I could investigate.

Is there a "good" reason to force this evolution (except the fact that database is configured in another place, since there is no real difference of having it in a single XML - Waarp - or multiples ones - Tomcat + Waarp since you still need to have specific configuration for Waarp -) ?

**Comment by Astr0boy** [comment]
Well we did had some cases where our customer network was not 100% reliable and that cause some insert/update issue for other kind of transfers, so we did implements a db pool connector allowing retries even if the db is down or network issue for few minutes.
So I was thinking that if it will worth to use such feature for r66 as well.
However, not sure how the r66 transfer will react if the db is not available for few minutes...(we are using MySQL db). Maybe it would worth having a H2 in-memory db for r66.

**Comment by fredericBregier** [comment]
On Server side, R66 manage already a pool and retry, but in case it does not work, as the database is the center of the "context" (reliability), it shall be in error if it really cannot reach the database.

On Client side:

- either you use a submit method (but then depends on the database but only on submission part, so retry is possible outside), 
- either you use no database mode (XML based), 
- either you use the database from same server (server is on the same host than the client), 
- either you use database mode with a H2 database, either in memory mode or local mode (file based) ; I would recommend however the file based since in memory will imply to recreate the database each time (since volatile)...

**Comment by Astr0boy** [comment]
Thanks for your valuable help as usual :)
option 1 would have been the best but the only issue I have if that I need then to correlate the status of the r66 transfer with the status of my file (and then store somewhere the special Id).
I'll go for option 3 in direct transfer (at least in a first time :) )
