### ISSUE TITLE
Class org.waarp.openr66.configuration.Configuration

### ISSUE THREAD

**Issue by Astr0boy** [waarp/WaarpR66#187]
Hi Frédéric,

Why not having a class org.waarp.openr66.configuration.Configuration with getter and setter to create the R66 configuration ? As far as I can see we can only use the FileBasedConfiguration class and need to use the setClientConfigurationFromXml method for example to set the client configuration.
It would help to override some value (nb of retries, snmp...) or populate the value from DB instead of  XML file.

**Comment by fredericBregier** [comment]
The class you search for is:

[(https://github.com/waarp/WaarpR66/blob/wNetty41/src/main/java/org/waarp/openr66/protocol/configuration/Configuration.java)]

Which will be available in the next release as is (with getters and setters). That's one of the "improvement" in the code we create lastly.

The FileBasedConfiguration is getting information from XML file.

Of course, changing to another way (database based) suppose to:

- rewrite the startup procedure (in order to change from FileBasedConfiguration to something else)
- ensure your own table for that configuration with your own way to populate it

Since some information are sensible (as the password, the ssl key), we decided to still have a XML configuration file that need to be protected against access through protection to the server itself.

However it is valid to try to have (all or not) information in database. The issue is at least: which "record" in the table is for the current host if you share this database among several servers (which is supported). You still need an option to pass to the server, as for instance the database connection and its "hostid" I believe.

**Comment by Astr0boy** [comment]
Ok perfect I'll have a look at the class :)
Well, at least even if there's a XML file I would like to be able to override some value (for example the workingPath, inPath as the data are located in a different storage location than the runtime part).
Regarding the hostid it's contained as a parameter in the context deployed on Tomcat, so when the context is starting we know the hostid.
Also, just a question related to several hostid, you can't use several hostid in server mode running on the same JVM, right (except for nossl and ssl mode) ?

**Comment by fredericBregier** [comment]
For the in, out and so on pathes, you can specify absolute path in the rule, therefore even out of R66 home. R66 default in, out and so on are indeed based on the R66 home and considered as relative path to R66 home. However nothing prevent you to set a link to the real target/source/work if needed.

The reason behind this "relative path" is to be able to share the rules among several servers using the same database, then either global IN/OUT or relative path for IN/OUT in rule are relative to the server R66 home running the rule.

Of course you can also make as you specify... ;-)

As for the host id:

- You can have on the same host many R66 servers (so with different ids), as long as they don't share the same "ports".
- You can have on the same host one R66 server (with one id, respect to ssl/nossl), but you can also have "alias" for this very same host id. See: at the end of https://waarp.github.io/Waarp/WaarpR66Options.html the Aliases part, also avaible through HTTPS Web Admin interface (see the SystemScreen at https://waarp.github.io/Waarp/WaarpR66WebAdministration.html and the very same information on Aliases too)

**Comment by Astr0boy** [comment]
Thanks again Frédéric. I used in fact the rule for the in and out path.
I'll have a look at the alias.
