### ISSUE TITLE
PeSIT specification

### ISSUE THREAD

**Issue by gulecroc** [waarp/WaarpR66#211]
Hello,

I would like to know if you have any PeSIT specification ?
We are using CFT/Gateway with PeSIT and i would like to impl this procotol too.

Regards,
Guillaume

**Comment by fredericBregier** [comment]
We do not implement pesit. The specifications were public sometimes ago but not easy now to find . 
Moreover any implementation has specifics which tends to not really support other implementations (except considering restriction in usage since extensions bring improvements).
This protocol is quite complex , giving a lot of incompatibility issues between implementations.

If you're using axway cft, you may contact reseller to get access to libraries that could be used in your context, of course not for free.
