### ISSUE TITLE
Rest Authentication on Waarp, question

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#218]
Hi,

I've managed to authenticate myself on rest interface. But login fails when host port equal o greater than zero as shown here https://github.com/waarp/WaarpR66/blob/4a17c3e8f802b7ea60197d63a3352c39c57c50b1/src/main/java/org/waarp/openr66/context/authentication/R66Auth.java#L289. 

By setting host port parameter equal to -1 for server on the interface, I got it working but what's the reason behind? I need to create a specific host with port equal to -1 , only for rest authentication?

Regards

Alex

**Comment by fredericBregier** [comment]
- Host port with 0 = client host (so no real port assigned) but possibly certificate
- Host port with -1 = user authentication, meaning no port at all neither certificate

**Comment by alexbarta** [comment]
Ok got it. But what do you mean exactly by certificate? JKS keystore certificate ?
Thanks for the reply.

Alex

**Comment by fredericBregier** [comment]
Hmm, I was perhaps to short or to quick in the response.
Every host in the database has at least 1 name, 1 port and 1 password (encrypted)
- if port > 0, it is a server and could be called back at any time
- if port = 0, it is a client (or so) and could only be the source of the requests (so the server cannot calles back the client since no port is defined)
- if port < 0, this is an admin account (with priviligèes through the XMlL configuration) and of course cannot be called back

On the certificate, I was wrong, all could have a certificate (depending if you are in dual TLS authentication mode). So if in dual mode, all hosts (whatever > < or = 0) when using "waarp protocol" port. If dual is on, both certificate (client and server should be shared (public part of course).

In HTTPS or REST mode, no control (if I'm correct) is done for the client on certificate side, so < 0 does not mean any JKS for that (again, except if I really forgot there is there too a dual possible valisation). Of course the client should have the public certificate of the server to validate the TLS connection.

**Comment by alexbarta** [comment]
Ok that makes sense. I think you can close this one.

Thanks again.

Alex

**Comment by fredericBregier** [comment]
Thank you !
